services:
  backend-highlight:
    container_name: backend-highlight
    image: ${BACKEND_IMAGE_NAME:-ghcr.io/highlight/highlight-backend:latest}
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - highlight-data:/highlight-data
      - ./backend/localhostssl/server.key:/build/env.enc  
      - ./backend/localhostssl/server.crt:/build/env.enc 
    env_file: .env

  frontend-highlight:
    container_name: frontend-highlight
    image: ${FRONTEND_IMAGE_NAME:-ghcr.io/highlight/highlight-frontend:latest}
    restart: on-failure
    ports:
      - "3001:3000"  
      - "6006:6006"
      - "8080:8080"
    env_file: .env

volumes:
  highlight-data:
