services:
  backend:
    container_name: backend
    image: ${BACKEND_IMAGE_NAME:-ghcr.io/highlight/highlight-backend:latest}
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - highlight-data:/highlight-data
      - ./backend/env.enc:/build/env.enc
      - ./backend/env.enc.dgst:/build/env.enc.dgst
    env_file: .env

  frontend:
    container_name: frontend
    image: ${FRONTEND_IMAGE_NAME:-ghcr.io/highlight/highlight-frontend:latest}
    restart: on-failure
    ports:
      - "3001:3000" 
      - "6006:6006"
      - "8080:8080"
    env_file: .env

volumes:
  highlight-data:
